212 remove unnecessary files
IPPL-framework/ippl pull request #214
Opened 2023-08-29 07:48 UTC by srikrrish

2023-08-29 07:49 UTC, srikrrish commented
This still needs to be tested!

2024-03-26 06:41 UTC, srikrrish commented
This is ready now! The Tuple is fixed thanks to @manuel5975p and I tested again. Everything seems to compile and work fine.

2024-03-26 08:39 UTC, matt-frey requested changes
Looks generally good. Two minor things.

2024-03-26 08:39 UTC, matt-frey commented on README.md
> +All the new developments of IPPL are merged in to the `master` branch which can make it potentially unstable from time to time. So if you want a stable and more tested version
"in to" --> "into"

2024-03-26 08:39 UTC, matt-frey commented on README.md
> +please checkout the tagged branch correspodning to the last release (e.g. `git checkout tags/IPPL-x.x.x`). Otherwise if you want the latest developments go with the master with the above caveat in mi
"last" --> "latest"

2024-03-26 09:23 UTC, matt-frey approved these changes
Thanks for doing this!

2024-03-26 10:54 UTC, aaadelmann approved these changes

2024-03-26 11:04 UTC, merged