Remove aggr. init. for Apple Clang
IPPL-framework/ippl pull request #262
Opened 2024-03-15 08:34 UTC by manuel5975p

Explicitly add constructors to TupleImpl<i, N, T>
```cpp
        TupleImpl<i, N, T>()
            requires(std::is_default_constructible_v<T>)
         = default;
        TupleImpl<i, N, T>(const T& t) : val(t){}
        TupleImpl<i, N, T>(T&& t) : val(std::forward<T>(t)){}
```
in order not to rely on C++20's aggregate initialization since apple clang [doesn't implement that feature](https://en.cppreference.com/w/cpp/compiler_support/20)
The red cell is Apple Clang's support for this feature.
![image](https://github.com/IPPL-framework/ippl/assets/5041338/642f7b15-a4da-4ff7-bf94-4aec66724236)

2024-03-15 13:02 UTC, Arc676 commented
The changes seem fine but the PR is lacking in motivation. What is the benefit of adding this constructor? The custom tuple implementation is only relevant for machines running GCC12 + CUDA 12.1, which implies not using Apple Clang. Does IPPL fail to compile on Macs when using the standard library tuple implementation?

2024-03-15 13:56 UTC, manuel5975p commented
I just don't want apple clang users to get bogged down by the TestTuple executable, which doesn't make sense / work with std::tuple

2024-03-16 12:31 UTC, Arc676 reviewed
Never mind, got confused. Was thinking of the variant type.

2024-03-16 12:32 UTC, Arc676 approved these changes

2024-03-16 12:33 UTC, Arc676 requested changes
Actually, on second thought, if this is a compiler-specific fix that deviates from the STL implementation (I assume most of this code is adapted from GNU stdlibc++) just because of implementation choices in Clang, I would surround this with an `#ifdef` to enable this change only for the affected compiler.

2024-03-16 12:44 UTC, Arc676 approved these changes

2024-03-17 08:59 UTC, aaadelmann approved these changes

2024-03-18 10:03 UTC, merged